#include "NetFields.hpp"
#include "ClientSnapshotData.hpp"

namespace Iswenzz
{
	//static int GetMinBitCount(int x)
	//{
	//	return 32 - __builtin_clz(x);
	//}

	#define NETF(x) const_cast<char *>(# x), (int)&((entityState_t*)0)->x

	netField_t entityStateFields[] =
	{
		{ NETF(eType), 8, 0 },
		{ NETF(lerp.eFlags), -98, 0 },
		{ NETF(lerp.pos.trBase[0]), -92, 0 },
		{ NETF(lerp.pos.trBase[1]), -91, 0 },
		{ NETF(lerp.pos.trBase[2]), -90, 0 },
		{ NETF(events[0]), -94, 0 },
		{ NETF(eventSequence), 8, 0 },
		{ NETF(weapon), 7, 0 },
		{ NETF(weaponModel), 4, 0 },
		{ NETF(eventParms[0]), -93, 0 },
		{ NETF(surfType), 8, 0 },
		{ NETF(lerp.u.anonymous.data[0]), 32, 0 },
		{ NETF(time2), -97, 0 },
		{ NETF(index), 10, 0 },
		{ NETF(solid), 24, 0 },
		{ NETF(un2), 32, 0 },
		{ NETF(groundEntityNum), -96, 0 },
		{ NETF(un1), 8, 0 },
		{ NETF(lerp.apos.trBase[1]), -100, 0 },
		{ NETF(lerp.apos.trBase[0]), -100, 0 },
		{ NETF(clientNum), 7, 0 },
		{ NETF(lerp.pos.trDelta[0]), 0, 0 },
		{ NETF(lerp.pos.trDelta[1]), 0, 0 },
		{ NETF(lerp.pos.trDelta[2]), 0, 0 },
		{ NETF(events[1]), -94, 0 },
		{ NETF(events[2]), -94, 0 },
		{ NETF(eventParms[1]), -93, 0 },
		{ NETF(eventParms[2]), -93, 0 },
		{ NETF(lerp.pos.trTime), -97, 0 },
		{ NETF(lerp.pos.trType), 8, 0 },
		{ NETF(eventParm), -93, 0 },
		{ NETF(lerp.apos.trType), 8, 0 },
		{ NETF(events[3]), -94, 0 },
		{ NETF(lerp.apos.trBase[2]), -100, 0 },
		{ NETF(lerp.apos.trTime), 32, 0 },
		{ NETF(lerp.apos.trDelta[0]), 0, 0 },
		{ NETF(lerp.apos.trDelta[2]), 0, 0 },
		{ NETF(eventParms[3]), -93, 0 },
		{ NETF(lerp.pos.trDuration), 32, 0 },
		{ NETF(lerp.apos.trDelta[1]), 0, 0 },
		{ NETF(attackerEntityNum), 10, 0 },
		{ NETF(fWaistPitch), 0, 0 },
		{ NETF(fTorsoPitch), 0, 0 },
		{ NETF(iHeadIcon), 4, 0 },
		{ NETF(iHeadIconTeam), 2, 0 },
		{ NETF(lerp.apos.trDuration), 32, 0 },
		{ NETF(torsoAnim), 10, 0 },
		{ NETF(legsAnim), 10, 0 },
		{ NETF(loopSound), 8, 0 },
		{ NETF(otherEntityNum), 10, 0 },
		{ NETF(lerp.u.anonymous.data[1]), 32, 0 },
		{ NETF(lerp.u.anonymous.data[2]), 32, 0 },
		{ NETF(lerp.u.anonymous.data[3]), 32, 0 },
		{ NETF(lerp.u.anonymous.data[4]), 32, 0 },
		{ NETF(lerp.u.anonymous.data[5]), 32, 0 },
		{ NETF(partBits[0]), 32, 0 },
		{ NETF(partBits[1]), 32, 0 },
		{ NETF(partBits[2]), 32, 0 },
		{ NETF(partBits[3]), 32, 0 },
	};

	netField_t playerEntityStateFields[] =
	{
		{ NETF(eType), 8, 1 },
		{ NETF(lerp.pos.trBase[0]), -92, 2 },
		{ NETF(lerp.pos.trBase[1]), -91, 2 },
		{ NETF(lerp.u.player.movementDir), -8, 0 },
		{ NETF(lerp.apos.trBase[1]), -100, 0 },
		{ NETF(lerp.pos.trBase[2]), -90, 0 },
		{ NETF(eventSequence), 8, 0 },
		{ NETF(lerp.apos.trBase[0]), -100, 0 },
		{ NETF(legsAnim), 10, 0 },
		{ NETF(torsoAnim), 10, 0 },
		{ NETF(lerp.eFlags), -98, 0 },
		{ NETF(events[0]), -94, 0 },
		{ NETF(events[1]), -94, 0 },
		{ NETF(events[2]), -94, 0 },
		{ NETF(events[3]), -94, 0 },
		{ NETF(eventParms[1]), -93, 0 },
		{ NETF(eventParms[0]), -93, 0 },
		{ NETF(eventParms[2]), -93, 0 },
		{ NETF(eventParms[3]), -93, 0 },
		{ NETF(groundEntityNum), -96, 0 },
		{ NETF(fTorsoPitch), 0, 0 },
		{ NETF(fWaistPitch), 0, 0 },
		{ NETF(solid), 24, 0 },
		{ NETF(weapon), 7, 0 },
		{ NETF(eventParm), -93, 0 },
		{ NETF(lerp.pos.trType), 8, 0 },
		{ NETF(lerp.apos.trType), 8, 0 },
		{ NETF(lerp.apos.trBase[2]), -100, 0 },
		{ NETF(clientNum), 7, 0 },
		{ NETF(otherEntityNum), 10, 0 },
		{ NETF(weaponModel), 4, 0 },
		{ NETF(iHeadIcon), 4, 0 },
		{ NETF(iHeadIconTeam), 2, 0 },
		{ NETF(lerp.u.player.leanf), 0, 0 },
		{ NETF(lerp.pos.trDelta[1]), 0, 1 },
		{ NETF(lerp.pos.trDelta[0]), 0, 1 },
		{ NETF(lerp.pos.trDuration), 32, 1 },
		{ NETF(lerp.pos.trTime), -97, 1 },
		{ NETF(lerp.pos.trDelta[2]), 0, 1 },
		{ NETF(surfType), 8, 1 },
		{ NETF(un1), 8, 1 },
		{ NETF(index), 10, 1 },
		{ NETF(lerp.apos.trDelta[0]), 0, 1 },
		{ NETF(lerp.apos.trDelta[1]), 0, 1 },
		{ NETF(lerp.apos.trDelta[2]), 0, 1 },
		{ NETF(time2), -97, 1 },
		{ NETF(loopSound), 8, 1 },
		{ NETF(attackerEntityNum), 10, 1 },
		{ NETF(lerp.apos.trTime), 32, 1 },
		{ NETF(lerp.apos.trDuration), 32, 1 },
		{ NETF(lerp.u.anonymous.data[2]), 32, 1 },
		{ NETF(lerp.u.anonymous.data[3]), 32, 1 },
		{ NETF(lerp.u.anonymous.data[4]), 32, 1 },
		{ NETF(lerp.u.anonymous.data[5]), 32, 1 },
		{ NETF(un2), 32, 1 },
		{ NETF(partBits[0]), 32, 1 },
		{ NETF(partBits[1]), 32, 1 },
		{ NETF(partBits[2]), 32, 1 },
		{ NETF(partBits[3]), 32, 1 },
	};

	netField_t corpseEntityStateFields[] =
	{
		{ NETF(eType), 8, 1 },
		{ NETF(lerp.eFlags), -98, 0 },
		{ NETF(lerp.pos.trTime), -97, 0 },
		{ NETF(lerp.pos.trBase[0]), -92, 0 },
		{ NETF(lerp.pos.trBase[1]), -91, 0 },
		{ NETF(lerp.pos.trBase[2]), -90, 0 },
		{ NETF(lerp.pos.trType), 8, 0 },
		{ NETF(lerp.apos.trType), 8, 0 },
		{ NETF(lerp.apos.trBase[1]), -100, 0 },
		{ NETF(clientNum), 7, 0 },
		{ NETF(legsAnim), 10, 0 },
		{ NETF(lerp.apos.trBase[0]), -100, 0 },
		{ NETF(lerp.apos.trBase[2]), -100, 0 },
		{ NETF(torsoAnim), 10, 0 },
		{ NETF(groundEntityNum), -96, 0 },
		{ NETF(lerp.pos.trDelta[0]), 0, 0 },
		{ NETF(lerp.pos.trDelta[1]), 0, 0 },
		{ NETF(lerp.pos.trDelta[2]), 0, 0 },
		{ NETF(lerp.u.player.movementDir), -8, 1 },
		{ NETF(eventSequence), 8, 1 },
		{ NETF(events[0]), -94, 1 },
		{ NETF(events[1]), -94, 1 },
		{ NETF(events[2]), -94, 1 },
		{ NETF(events[3]), -94, 1 },
		{ NETF(fTorsoPitch), 0, 1 },
		{ NETF(eventParms[1]), -93, 1 },
		{ NETF(eventParms[0]), -93, 1 },
		{ NETF(eventParms[2]), -93, 1 },
		{ NETF(weapon), 7, 1 },
		{ NETF(weaponModel), 4, 1 },
		{ NETF(eventParms[3]), -93, 1 },
		{ NETF(solid), 24, 1 },
		{ NETF(lerp.pos.trDuration), 32, 1 },
		{ NETF(fWaistPitch), 0, 1 },
		{ NETF(eventParm), -93, 1 },
		{ NETF(iHeadIcon), 4, 1 },
		{ NETF(iHeadIconTeam), 2, 1 },
		{ NETF(surfType), 8, 1 },
		{ NETF(un1), 8, 1 },
		{ NETF(otherEntityNum), 10, 1 },
		{ NETF(index), 10, 1 },
		{ NETF(lerp.apos.trDelta[0]), 0, 1 },
		{ NETF(lerp.apos.trDelta[1]), 0, 1 },
		{ NETF(lerp.apos.trDelta[2]), 0, 1 },
		{ NETF(time2), -97, 1 },
		{ NETF(loopSound), 8, 1 },
		{ NETF(attackerEntityNum), 10, 1 },
		{ NETF(lerp.apos.trTime), 32, 1 },
		{ NETF(lerp.u.player.leanf), 0, 1 },
		{ NETF(lerp.apos.trDuration), 32, 1 },
		{ NETF(un2), 32, 1 },
		{ NETF(lerp.u.anonymous.data[2]), 32, 1 },
		{ NETF(lerp.u.anonymous.data[3]), 32, 1 },
		{ NETF(lerp.u.anonymous.data[4]), 32, 1 },
		{ NETF(lerp.u.anonymous.data[5]), 32, 1 },
		{ NETF(partBits[0]), 32, 1 },
		{ NETF(partBits[1]), 32, 1 },
		{ NETF(partBits[2]), 32, 1 },
		{ NETF(partBits[3]), 32, 1 },
	};

	netField_t itemEntityStateFields[] =
	{
		{ NETF(eType), 8, 0 },
		{ NETF(lerp.pos.trBase[2]), -90, 0 },
		{ NETF(lerp.pos.trBase[1]), -91, 0 },
		{ NETF(lerp.pos.trBase[0]), -92, 0 },
		{ NETF(lerp.pos.trTime), -97, 0 },
		{ NETF(lerp.pos.trType), 8, 2 },
		{ NETF(lerp.pos.trDelta[2]), 0, 2 },
		{ NETF(lerp.pos.trDelta[0]), 0, 2 },
		{ NETF(lerp.pos.trDelta[1]), 0, 0 },
		{ NETF(clientNum), 7, 2 },
		{ NETF(lerp.apos.trBase[1]), -100, 0 },
		{ NETF(lerp.apos.trType), 8, 2 },
		{ NETF(lerp.apos.trTime), -97, 2 },
		{ NETF(lerp.apos.trDelta[0]), 0, 2 },
		{ NETF(lerp.apos.trDelta[1]), 0, 2 },
		{ NETF(lerp.apos.trDelta[2]), 0, 0 },
		{ NETF(index), 10, 0 },
		{ NETF(lerp.apos.trBase[2]), -100, 0 },
		{ NETF(groundEntityNum), -96, 0 },
		{ NETF(lerp.pos.trDuration), 32, 0 },
		{ NETF(lerp.apos.trBase[0]), -100, 0 },
		{ NETF(solid), 24, 0 },
		{ NETF(eventParm), -93, 0 },
		{ NETF(lerp.eFlags), -98, 0 },
		{ NETF(eventSequence), 8, 0 },
		{ NETF(events[0]), -94, 0 },
		{ NETF(eventParms[0]), -93, 0 },
		{ NETF(weapon), 7, 0 },
		{ NETF(weaponModel), 4, 0 },
		{ NETF(surfType), 8, 0 },
		{ NETF(otherEntityNum), 10, 0 },
		{ NETF(lerp.u.anonymous.data[0]), 32, 0 },
		{ NETF(lerp.u.anonymous.data[1]), 32, 0 },
		{ NETF(lerp.u.anonymous.data[2]), 32, 0 },
		{ NETF(eventParms[1]), -93, 0 },
		{ NETF(eventParms[2]), -93, 0 },
		{ NETF(eventParms[3]), -93, 0 },
		{ NETF(events[1]), -94, 0 },
		{ NETF(events[2]), -94, 0 },
		{ NETF(events[3]), -94, 0 },
		{ NETF(attackerEntityNum), 10, 0 },
		{ NETF(un1), 8, 0 },
		{ NETF(time2), -97, 0 },
		{ NETF(loopSound), 8, 0 },
		{ NETF(un2), 32, 0 },
		{ NETF(legsAnim), 10, 1 },
		{ NETF(torsoAnim), 10, 1 },
		{ NETF(fTorsoPitch), 0, 1 },
		{ NETF(fWaistPitch), 0, 1 },
		{ NETF(iHeadIcon), 4, 1 },
		{ NETF(iHeadIconTeam), 2, 1 },
		{ NETF(lerp.apos.trDuration), 32, 1 },
		{ NETF(lerp.u.anonymous.data[3]), 32, 1 },
		{ NETF(lerp.u.anonymous.data[4]), 32, 1 },
		{ NETF(lerp.u.anonymous.data[5]), 32, 1 },
		{ NETF(partBits[0]), 32, 1 },
		{ NETF(partBits[1]), 32, 1 },
		{ NETF(partBits[2]), 32, 1 },
		{ NETF(partBits[3]), 32, 1 },
	};

	netField_t missleEntityStateFields[] =
	{
		{ NETF(eType), 8, 0 },
		{ NETF(lerp.pos.trBase[1]), -91, 0 },
		{ NETF(lerp.pos.trBase[0]), -92, 0 },
		{ NETF(lerp.pos.trDelta[0]), 0, 0 },
		{ NETF(lerp.pos.trDelta[1]), 0, 0 },
		{ NETF(lerp.pos.trDelta[2]), 0, 0 },
		{ NETF(lerp.apos.trBase[2]), -100, 0 },
		{ NETF(lerp.apos.trBase[0]), -100, 0 },
		{ NETF(lerp.pos.trBase[2]), -90, 0 },
		{ NETF(lerp.pos.trTime), -97, 0 },
		{ NETF(lerp.apos.trTime), -97, 0 },
		{ NETF(lerp.apos.trDelta[0]), 0, 0 },
		{ NETF(eventSequence), 8, 0 },
		{ NETF(groundEntityNum), -96, 0 },
		{ NETF(lerp.apos.trBase[1]), -100, 0 },
		{ NETF(lerp.pos.trType), 8, 0 },
		{ NETF(lerp.apos.trType), 8, 0 },
		{ NETF(lerp.eFlags), -98, 0 },
		{ NETF(surfType), 8, 0 },
		{ NETF(lerp.apos.trDelta[2]), 0, 0 },
		{ NETF(lerp.u.missile.launchTime), -97, 0 },
		{ NETF(weapon), 7, 0 },
		{ NETF(eventParms[0]), -93, 0 },
		{ NETF(events[0]), -94, 0 },
		{ NETF(events[1]), -94, 0 },
		{ NETF(index), 10, 0 },
		{ NETF(clientNum), 7, 0 },
		{ NETF(eventParms[1]), -93, 0 },
		{ NETF(events[2]), -94, 0 },
		{ NETF(eventParms[2]), -93, 0 },
		{ NETF(un2), 1, 0 },
		{ NETF(events[3]), -94, 0 },
		{ NETF(eventParms[3]), -93, 0 },
		{ NETF(weaponModel), 4, 0 },
		{ NETF(eventParm), -93, 0 },
		{ NETF(un1), 8, 0 },
		{ NETF(otherEntityNum), 10, 0 },
		{ NETF(lerp.apos.trDelta[1]), 0, 0 },
		{ NETF(attackerEntityNum), 10, 0 },
		{ NETF(lerp.pos.trDuration), 32, 0 },
		{ NETF(loopSound), 8, 0 },
		{ NETF(lerp.u.anonymous.data[1]), 32, 0 },
		{ NETF(lerp.u.anonymous.data[2]), 32, 0 },
		{ NETF(solid), 24, 0 },
		{ NETF(time2), -97, 0 },
		{ NETF(legsAnim), 10, 1 },
		{ NETF(torsoAnim), 10, 1 },
		{ NETF(fTorsoPitch), 0, 1 },
		{ NETF(fWaistPitch), 0, 1 },
		{ NETF(iHeadIcon), 4, 1 },
		{ NETF(iHeadIconTeam), 2, 1 },
		{ NETF(lerp.apos.trDuration), 32, 1 },
		{ NETF(lerp.u.anonymous.data[3]), 32, 1 },
		{ NETF(lerp.u.anonymous.data[4]), 32, 1 },
		{ NETF(lerp.u.anonymous.data[5]), 32, 1 },
		{ NETF(partBits[0]), 32, 1 },
		{ NETF(partBits[1]), 32, 1 },
		{ NETF(partBits[2]), 32, 1 },
		{ NETF(partBits[3]), 32, 1 },
	};

	netField_t scriptMoverStateFields[] =
	{
		{ NETF(eType), 8, 0 },
		{ NETF(lerp.pos.trBase[0]), -92, 0 },
		{ NETF(lerp.pos.trBase[1]), -91, 0 },
		{ NETF(lerp.pos.trBase[2]), -90, 0 },
		{ NETF(eventSequence), 8, 0 },
		{ NETF(lerp.pos.trTime), -97, 0 },
		{ NETF(index), 10, 0 },
		{ NETF(lerp.pos.trDuration), 32, 0 },
		{ NETF(lerp.pos.trType), 8, 0 },
		{ NETF(lerp.apos.trBase[1]), -100, 0 },
		{ NETF(lerp.pos.trDelta[2]), 0, 0 },
		{ NETF(lerp.apos.trDelta[0]), 0, 0 },
		{ NETF(lerp.apos.trType), 8, 0 },
		{ NETF(lerp.pos.trDelta[0]), 0, 0 },
		{ NETF(lerp.pos.trDelta[1]), 0, 0 },
		{ NETF(lerp.apos.trDelta[1]), 0, 0 },
		{ NETF(lerp.apos.trDelta[2]), 0, 0 },
		{ NETF(lerp.apos.trBase[2]), -100, 0 },
		{ NETF(lerp.apos.trBase[0]), -100, 0 },
		{ NETF(eventParms[0]), -93, 0 },
		{ NETF(partBits[0]), 32, 0 },
		{ NETF(events[0]), -94, 0 },
		{ NETF(lerp.apos.trTime), 32, 0 },
		{ NETF(partBits[1]), 32, 0 },
		{ NETF(events[1]), -94, 0 },
		{ NETF(eventParms[1]), -93, 0 },
		{ NETF(eventParms[2]), -93, 0 },
		{ NETF(events[2]), -94, 0 },
		{ NETF(lerp.apos.trDuration), 32, 0 },
		{ NETF(eventParms[3]), -93, 0 },
		{ NETF(events[3]), -94, 0 },
		{ NETF(loopSound), 8, 0 },
		{ NETF(solid), 24, 0 },
		{ NETF(lerp.eFlags), -98, 0 },
		{ NETF(groundEntityNum), -96, 0 },
		{ NETF(clientNum), 7, 0 },
		{ NETF(eventParm), -93, 0 },
		{ NETF(weapon), 7, 0 },
		{ NETF(surfType), 8, 0 },
		{ NETF(otherEntityNum), 10, 0 },
		{ NETF(lerp.u.anonymous.data[0]), 32, 0 },
		{ NETF(lerp.u.anonymous.data[1]), 32, 0 },
		{ NETF(lerp.u.anonymous.data[2]), 32, 0 },
		{ NETF(weaponModel), 4, 0 },
		{ NETF(time2), -97, 0 },
		{ NETF(un2), 32, 0 },
		{ NETF(un1), 8, 0 },
		{ NETF(attackerEntityNum), 10, 0 },
		{ NETF(fWaistPitch), 0, 0 },
		{ NETF(fTorsoPitch), 0, 0 },
		{ NETF(iHeadIcon), 4, 0 },
		{ NETF(iHeadIconTeam), 2, 0 },
		{ NETF(torsoAnim), 10, 0 },
		{ NETF(legsAnim), 10, 0 },
		{ NETF(lerp.u.anonymous.data[3]), 32, 0 },
		{ NETF(lerp.u.anonymous.data[4]), 32, 0 },
		{ NETF(lerp.u.anonymous.data[5]), 32, 0 },
		{ NETF(partBits[2]), 32, 0 },
		{ NETF(partBits[3]), 32, 0 },
	};

	netField_t soundBlendEntityStateFields[] =
	{
		{ NETF(eType), 8, 1 },
		{ NETF(lerp.pos.trTime), -97, 0 },
		{ NETF(lerp.pos.trBase[0]), -92, 0 },
		{ NETF(lerp.pos.trBase[1]), -91, 0 },
		{ NETF(lerp.pos.trDelta[0]), 0, 0 },
		{ NETF(lerp.pos.trDelta[1]), 0, 0 },
		{ NETF(lerp.apos.trBase[1]), -100, 0 },
		{ NETF(lerp.pos.trBase[2]), -90, 0 },
		{ NETF(lerp.pos.trDelta[2]), 0, 0 },
		{ NETF(lerp.apos.trBase[0]), -100, 0 },
		{ NETF(eventSequence), 8, 0 },
		{ NETF(legsAnim), 10, 0 },
		{ NETF(surfType), 8, 0 },
		{ NETF(otherEntityNum), 10, 0 },
		{ NETF(un1), 8, 0 },
		{ NETF(lerp.eFlags), -98, 0 },
		{ NETF(groundEntityNum), -96, 0 },
		{ NETF(clientNum), 7, 0 },
		{ NETF(events[0]), -94, 0 },
		{ NETF(events[1]), -94, 0 },
		{ NETF(events[2]), -94, 0 },
		{ NETF(weapon), 7, 0 },
		{ NETF(weaponModel), 4, 0 },
		{ NETF(eventParms[1]), -93, 0 },
		{ NETF(eventParms[0]), -93, 0 },
		{ NETF(eventParms[2]), -93, 0 },
		{ NETF(index), 10, 0 },
		{ NETF(lerp.pos.trType), 8, 0 },
		{ NETF(lerp.apos.trType), 8, 0 },
		{ NETF(events[3]), -94, 0 },
		{ NETF(lerp.apos.trBase[2]), -100, 0 },
		{ NETF(lerp.apos.trTime), 32, 0 },
		{ NETF(lerp.apos.trDelta[0]), 0, 0 },
		{ NETF(lerp.apos.trDelta[2]), 0, 0 },
		{ NETF(torsoAnim), 10, 0 },
		{ NETF(eventParms[3]), -93, 0 },
		{ NETF(solid), 24, 0 },
		{ NETF(lerp.pos.trDuration), 32, 0 },
		{ NETF(lerp.apos.trDelta[1]), 0, 0 },
		{ NETF(un2), 32, 0 },
		{ NETF(time2), -97, 0 },
		{ NETF(loopSound), 8, 0 },
		{ NETF(attackerEntityNum), 10, 0 },
		{ NETF(fWaistPitch), 0, 0 },
		{ NETF(fTorsoPitch), 0, 0 },
		{ NETF(iHeadIcon), 4, 0 },
		{ NETF(iHeadIconTeam), 2, 0 },
		{ NETF(eventParm), -93, 0 },
		{ NETF(lerp.u.soundBlend.lerp), 0, 0 },
		{ NETF(lerp.apos.trDuration), 32, 0 },
		{ NETF(lerp.u.anonymous.data[1]), 32, 1 },
		{ NETF(lerp.u.anonymous.data[2]), 32, 1 },
		{ NETF(lerp.u.anonymous.data[3]), 32, 1 },
		{ NETF(lerp.u.anonymous.data[4]), 32, 1 },
		{ NETF(lerp.u.anonymous.data[5]), 32, 1 },
		{ NETF(partBits[0]), 32, 1 },
		{ NETF(partBits[1]), 32, 1 },
		{ NETF(partBits[2]), 32, 1 },
		{ NETF(partBits[3]), 32, 1 },
	};

	netField_t fxStateFields[] =
	{
		{ NETF(eType), 8, 0 },
		{ NETF(time2), -97, 0 },
		{ NETF(lerp.apos.trBase[0]), -100, 0 },
		{ NETF(lerp.pos.trBase[0]), -92, 0 },
		{ NETF(lerp.pos.trBase[1]), -91, 0 },
		{ NETF(un1), 8, 0 },
		{ NETF(lerp.pos.trBase[2]), -90, 0 },
		{ NETF(lerp.apos.trBase[2]), -100, 0 },
		{ NETF(lerp.apos.trBase[1]), -100, 0 },
		{ NETF(lerp.pos.trTime), -97, 0 },
		{ NETF(lerp.pos.trType), 8, 0 },
		{ NETF(lerp.pos.trDelta[2]), 0, 0 },
		{ NETF(lerp.pos.trDelta[0]), 0, 0 },
		{ NETF(lerp.pos.trDelta[1]), 0, 0 },
		{ NETF(clientNum), 7, 0 },
		{ NETF(lerp.apos.trType), 8, 0 },
		{ NETF(lerp.apos.trTime), -97, 0 },
		{ NETF(lerp.apos.trDelta[0]), 0, 0 },
		{ NETF(lerp.apos.trDelta[1]), 0, 0 },
		{ NETF(lerp.apos.trDelta[2]), 0, 0 },
		{ NETF(index), 10, 0 },
		{ NETF(groundEntityNum), -96, 0 },
		{ NETF(lerp.pos.trDuration), 32, 0 },
		{ NETF(solid), 24, 0 },
		{ NETF(eventParm), -93, 0 },
		{ NETF(lerp.eFlags), -98, 0 },
		{ NETF(eventSequence), 8, 0 },
		{ NETF(events[0]), -94, 0 },
		{ NETF(eventParms[0]), -93, 0 },
		{ NETF(weapon), 7, 0 },
		{ NETF(weaponModel), 4, 0 },
		{ NETF(surfType), 8, 0 },
		{ NETF(otherEntityNum), 10, 0 },
		{ NETF(lerp.u.anonymous.data[0]), 32, 0 },
		{ NETF(lerp.u.anonymous.data[1]), 32, 0 },
		{ NETF(lerp.u.anonymous.data[2]), 32, 0 },
		{ NETF(eventParms[1]), -93, 0 },
		{ NETF(eventParms[2]), -93, 0 },
		{ NETF(eventParms[3]), -93, 0 },
		{ NETF(events[1]), -94, 0 },
		{ NETF(events[2]), -94, 0 },
		{ NETF(events[3]), -94, 0 },
		{ NETF(attackerEntityNum), 10, 0 },
		{ NETF(loopSound), 8, 0 },
		{ NETF(un2), 32, 0 },
		{ NETF(legsAnim), 10, 1 },
		{ NETF(torsoAnim), 10, 1 },
		{ NETF(fTorsoPitch), 0, 1 },
		{ NETF(fWaistPitch), 0, 1 },
		{ NETF(iHeadIcon), 4, 1 },
		{ NETF(iHeadIconTeam), 2, 1 },
		{ NETF(lerp.apos.trDuration), 32, 1 },
		{ NETF(lerp.u.anonymous.data[3]), 32, 1 },
		{ NETF(lerp.u.anonymous.data[4]), 32, 1 },
		{ NETF(lerp.u.anonymous.data[5]), 32, 1 },
		{ NETF(partBits[0]), 32, 1 },
		{ NETF(partBits[1]), 32, 1 },
		{ NETF(partBits[2]), 32, 1 },
		{ NETF(partBits[3]), 32, 1 },
	};

	netField_t loopFxEntityStateFields[] =
	{
		{ NETF(eType), 8, 1 },
		{ NETF(lerp.pos.trTime), -97, 0 },
		{ NETF(lerp.pos.trBase[0]), -92, 0 },
		{ NETF(lerp.pos.trBase[1]), -91, 0 },
		{ NETF(lerp.pos.trDelta[0]), 0, 0 },
		{ NETF(lerp.pos.trDelta[1]), 0, 0 },
		{ NETF(lerp.apos.trBase[1]), -100, 0 },
		{ NETF(lerp.pos.trBase[2]), -90, 0 },
		{ NETF(lerp.pos.trDelta[2]), 0, 0 },
		{ NETF(lerp.apos.trBase[0]), -100, 0 },
		{ NETF(lerp.u.loopFx.cullDist), 0, 0 },
		{ NETF(lerp.u.loopFx.period), 32, 0 },
		{ NETF(eventSequence), 8, 0 },
		{ NETF(legsAnim), 10, 0 },
		{ NETF(surfType), 8, 0 },
		{ NETF(otherEntityNum), 10, 0 },
		{ NETF(un1), 8, 0 },
		{ NETF(lerp.eFlags), -98, 0 },
		{ NETF(groundEntityNum), -96, 0 },
		{ NETF(clientNum), 7, 0 },
		{ NETF(events[0]), -94, 0 },
		{ NETF(events[1]), -94, 0 },
		{ NETF(events[2]), -94, 0 },
		{ NETF(weapon), 7, 0 },
		{ NETF(weaponModel), 4, 0 },
		{ NETF(eventParms[1]), -93, 0 },
		{ NETF(eventParms[0]), -93, 0 },
		{ NETF(eventParms[2]), -93, 0 },
		{ NETF(index), 10, 0 },
		{ NETF(lerp.pos.trType), 8, 0 },
		{ NETF(lerp.apos.trType), 8, 0 },
		{ NETF(events[3]), -94, 0 },
		{ NETF(lerp.apos.trBase[2]), -100, 0 },
		{ NETF(lerp.apos.trTime), 32, 0 },
		{ NETF(lerp.apos.trDelta[0]), 0, 0 },
		{ NETF(lerp.apos.trDelta[2]), 0, 0 },
		{ NETF(torsoAnim), 10, 0 },
		{ NETF(eventParms[3]), -93, 0 },
		{ NETF(solid), 24, 0 },
		{ NETF(lerp.pos.trDuration), 32, 0 },
		{ NETF(lerp.apos.trDelta[1]), 0, 0 },
		{ NETF(un2), 32, 0 },
		{ NETF(time2), -97, 0 },
		{ NETF(loopSound), 8, 0 },
		{ NETF(attackerEntityNum), 10, 0 },
		{ NETF(fWaistPitch), 0, 0 },
		{ NETF(fTorsoPitch), 0, 0 },
		{ NETF(iHeadIcon), 4, 0 },
		{ NETF(iHeadIconTeam), 2, 0 },
		{ NETF(eventParm), -93, 0 },
		{ NETF(lerp.apos.trDuration), 32, 0 },
		{ NETF(lerp.u.anonymous.data[2]), 32, 1 },
		{ NETF(lerp.u.anonymous.data[3]), 32, 1 },
		{ NETF(lerp.u.anonymous.data[4]), 32, 1 },
		{ NETF(lerp.u.anonymous.data[5]), 32, 1 },
		{ NETF(partBits[0]), 32, 1 },
		{ NETF(partBits[1]), 32, 1 },
		{ NETF(partBits[2]), 32, 1 },
		{ NETF(partBits[3]), 32, 1 },
	};

	netField_t helicopterEntityStateFields[] =
	{
		{ NETF(eType), 8, 1 },
		{ NETF(lerp.pos.trBase[0]), -92, 0 },
		{ NETF(lerp.apos.trBase[0]), -100, 0 },
		{ NETF(lerp.apos.trBase[2]), -100, 0 },
		{ NETF(lerp.u.vehicle.gunPitch), 0, 0 },
		{ NETF(lerp.pos.trBase[1]), -91, 0 },
		{ NETF(lerp.apos.trBase[1]), -100, 0 },
		{ NETF(lerp.pos.trBase[2]), -90, 0 },
		{ NETF(lerp.u.vehicle.gunYaw), 0, 0 },
		{ NETF(eventSequence), 8, 0 },
		{ NETF(un1.helicopterStage), 3, 0 },
		{ NETF(time2), -97, 0 },
		{ NETF(events[0]), -94, 0 },
		{ NETF(events[1]), -94, 0 },
		{ NETF(events[2]), -94, 0 },
		{ NETF(events[3]), -94, 0 },
		{ NETF(eventParms[1]), -93, 0 },
		{ NETF(eventParms[0]), -93, 0 },
		{ NETF(eventParms[2]), -93, 0 },
		{ NETF(eventParms[3]), -93, 0 },
		{ NETF(loopSound), 8, 0 },
		{ NETF(lerp.pos.trType), 8, 0 },
		{ NETF(lerp.apos.trType), 8, 0 },
		{ NETF(un2), 32, 0 },
		{ NETF(weapon), 7, 0 },
		{ NETF(lerp.u.vehicle.team), 8, 0 },
		{ NETF(weaponModel), 4, 0 },
		{ NETF(groundEntityNum), -96, 0 },
		{ NETF(eventParm), -93, 0 },
		{ NETF(lerp.pos.trDelta[0]), 0, 0 },
		{ NETF(lerp.pos.trDelta[1]), 0, 0 },
		{ NETF(lerp.pos.trDelta[2]), 0, 0 },
		{ NETF(lerp.pos.trTime), -97, 0 },
		{ NETF(legsAnim), 10, 0 },
		{ NETF(surfType), 8, 0 },
		{ NETF(otherEntityNum), 10, 0 },
		{ NETF(lerp.eFlags), -98, 0 },
		{ NETF(index), 10, 0 },
		{ NETF(lerp.u.vehicle.materialTime), -97, 0 },
		{ NETF(lerp.apos.trTime), 32, 0 },
		{ NETF(lerp.apos.trDelta[0]), 0, 0 },
		{ NETF(lerp.apos.trDelta[2]), 0, 0 },
		{ NETF(torsoAnim), 10, 0 },
		{ NETF(solid), 24, 0 },
		{ NETF(lerp.pos.trDuration), 32, 0 },
		{ NETF(lerp.apos.trDelta[1]), 0, 0 },
		{ NETF(attackerEntityNum), 10, 0 },
		{ NETF(fWaistPitch), 0, 0 },
		{ NETF(fTorsoPitch), 0, 0 },
		{ NETF(lerp.u.vehicle.bodyPitch), -100, 0 },
		{ NETF(lerp.u.vehicle.bodyRoll), -100, 0 },
		{ NETF(iHeadIcon), 4, 0 },
		{ NETF(iHeadIconTeam), 2, 0 },
		{ NETF(lerp.apos.trDuration), 32, 0 },
		{ NETF(partBits[0]), 32, 1 },
		{ NETF(partBits[1]), 32, 1 },
		{ NETF(partBits[2]), 32, 1 },
		{ NETF(partBits[3]), 32, 1 },
	};

	netField_t planeStateFields[] =
	{
		{ NETF(eType), 8, 1 },
		{ NETF(lerp.pos.trBase[0]), 0, 2 },
		{ NETF(lerp.pos.trBase[1]), 0, 2 },
		{ NETF(lerp.pos.trBase[2]), 0, 2 },
		{ NETF(index), 10, 2 },
		{ NETF(lerp.pos.trDelta[0]), 0, 2 },
		{ NETF(lerp.pos.trDelta[1]), 0, 2 },
		{ NETF(lerp.pos.trTime), -97, 2 },
		{ NETF(lerp.pos.trType), 8, 2 },
		{ NETF(lerp.pos.trDuration), 32, 2 },
		{ NETF(lerp.u.vehicle.team), 8, 2 },
		{ NETF(lerp.apos.trBase[1]), -100, 2 },
		{ NETF(lerp.pos.trDelta[2]), 0, 0 },
		{ NETF(events[0]), -94, 0 },
		{ NETF(eventSequence), 8, 0 },
		{ NETF(eventParms[0]), -93, 0 },
		{ NETF(events[1]), -94, 0 },
		{ NETF(eventParms[1]), -93, 0 },
		{ NETF(loopSound), 8, 0 },
		{ NETF(lerp.apos.trType), 8, 0 },
		{ NETF(eventParm), -93, 0 },
		{ NETF(weapon), 7, 0 },
		{ NETF(weaponModel), 4, 0 },
		{ NETF(surfType), 8, 0 },
		{ NETF(lerp.u.anonymous.data[0]), 32, 0 },
		{ NETF(time2), -97, 0 },
		{ NETF(solid), 24, 0 },
		{ NETF(un2), 32, 0 },
		{ NETF(groundEntityNum), -96, 0 },
		{ NETF(un1), 8, 0 },
		{ NETF(lerp.apos.trBase[0]), -100, 0 },
		{ NETF(clientNum), 7, 0 },
		{ NETF(events[2]), -94, 0 },
		{ NETF(eventParms[2]), -93, 0 },
		{ NETF(events[3]), -94, 0 },
		{ NETF(lerp.apos.trBase[2]), -100, 0 },
		{ NETF(lerp.apos.trTime), 32, 0 },
		{ NETF(lerp.apos.trDelta[0]), 0, 0 },
		{ NETF(lerp.apos.trDelta[2]), 0, 0 },
		{ NETF(eventParms[3]), -93, 0 },
		{ NETF(lerp.apos.trDelta[1]), 0, 0 },
		{ NETF(attackerEntityNum), 10, 0 },
		{ NETF(fWaistPitch), 0, 0 },
		{ NETF(fTorsoPitch), 0, 0 },
		{ NETF(iHeadIcon), 4, 0 },
		{ NETF(iHeadIconTeam), 2, 0 },
		{ NETF(lerp.apos.trDuration), 32, 0 },
		{ NETF(torsoAnim), 10, 0 },
		{ NETF(lerp.eFlags), -98, 0 },
		{ NETF(legsAnim), 10, 0 },
		{ NETF(otherEntityNum), 10, 0 },
		{ NETF(lerp.u.anonymous.data[1]), 32, 0 },
		{ NETF(lerp.u.anonymous.data[2]), 32, 0 },
		{ NETF(lerp.u.anonymous.data[3]), 32, 1 },
		{ NETF(lerp.u.anonymous.data[4]), 32, 1 },
		{ NETF(lerp.u.anonymous.data[5]), 32, 1 },
		{ NETF(partBits[0]), 32, 1 },
		{ NETF(partBits[1]), 32, 1 },
		{ NETF(partBits[2]), 32, 1 },
		{ NETF(partBits[3]), 32, 1 },
	};

	netField_t vehicleEntityStateFields[] =
	{
		{ NETF(eType), 8, 1 },
		{ NETF(lerp.pos.trTime), -97, 0 },
		{ NETF(lerp.pos.trBase[0]), -92, 0 },
		{ NETF(lerp.pos.trBase[1]), -91, 0 },
		{ NETF(lerp.pos.trDelta[0]), 0, 0 },
		{ NETF(lerp.pos.trDelta[1]), 0, 0 },
		{ NETF(lerp.u.vehicle.gunYaw), 0, 0 },
		{ NETF(lerp.apos.trBase[1]), -100, 0 },
		{ NETF(lerp.pos.trBase[2]), -90, 0 },
		{ NETF(lerp.pos.trDelta[2]), 0, 0 },
		{ NETF(lerp.apos.trBase[0]), -100, 0 },
		{ NETF(eventSequence), 8, 0 },
		{ NETF(legsAnim), 10, 0 },
		{ NETF(surfType), 8, 0 },
		{ NETF(otherEntityNum), 10, 0 },
		{ NETF(un1), 8, 0 },
		{ NETF(lerp.eFlags), -98, 0 },
		{ NETF(groundEntityNum), -96, 0 },
		{ NETF(clientNum), 7, 0 },
		{ NETF(events[0]), -94, 0 },
		{ NETF(events[1]), -94, 0 },
		{ NETF(events[2]), -94, 0 },
		{ NETF(weapon), 7, 0 },
		{ NETF(weaponModel), 4, 0 },
		{ NETF(eventParms[1]), -93, 0 },
		{ NETF(eventParms[0]), -93, 0 },
		{ NETF(eventParms[2]), -93, 0 },
		{ NETF(index), 10, 0 },
		{ NETF(lerp.u.vehicle.materialTime), -97, 0 },
		{ NETF(lerp.pos.trType), 8, 0 },
		{ NETF(lerp.apos.trType), 8, 0 },
		{ NETF(events[3]), -94, 0 },
		{ NETF(lerp.apos.trBase[2]), -100, 0 },
		{ NETF(lerp.apos.trTime), 32, 0 },
		{ NETF(lerp.apos.trDelta[0]), 0, 0 },
		{ NETF(lerp.apos.trDelta[2]), 0, 0 },
		{ NETF(torsoAnim), 10, 0 },
		{ NETF(eventParms[3]), -93, 0 },
		{ NETF(lerp.u.vehicle.gunPitch), 0, 0 },
		{ NETF(solid), 24, 0 },
		{ NETF(lerp.pos.trDuration), 32, 0 },
		{ NETF(lerp.apos.trDelta[1]), 0, 0 },
		{ NETF(un2), 32, 0 },
		{ NETF(time2), -97, 0 },
		{ NETF(loopSound), 8, 0 },
		{ NETF(attackerEntityNum), 10, 0 },
		{ NETF(fWaistPitch), 0, 0 },
		{ NETF(fTorsoPitch), 0, 0 },
		{ NETF(lerp.u.vehicle.bodyPitch), -100, 0 },
		{ NETF(lerp.u.vehicle.bodyRoll), -100, 0 },
		{ NETF(iHeadIcon), 4, 0 },
		{ NETF(iHeadIconTeam), 2, 0 },
		{ NETF(eventParm), -93, 0 },
		{ NETF(lerp.u.vehicle.steerYaw), 0, 0 },
		{ NETF(lerp.apos.trDuration), 32, 0 },
		{ NETF(partBits[0]), 32, 1 },
		{ NETF(partBits[1]), 32, 1 },
		{ NETF(partBits[2]), 32, 1 },
		{ NETF(partBits[3]), 32, 1 },
	};

	netField_t eventEntityStateFields[] =
	{
		{ NETF(eType), 8, 0 },
		{ NETF(lerp.pos.trBase[0]), -92, 0 },
		{ NETF(lerp.pos.trBase[1]), -91, 0 },
		{ NETF(lerp.pos.trBase[2]), -90, 0 },
		{ NETF(eventParm), -93, 0 },
		{ NETF(surfType), 8, 0 },
		{ NETF(otherEntityNum), 10, 0 },
		{ NETF(un1), 8, 0 },
		{ NETF(lerp.u.anonymous.data[0]), 32, 0 },
		{ NETF(lerp.u.anonymous.data[1]), 32, 0 },
		{ NETF(attackerEntityNum), 10, 0 },
		{ NETF(lerp.apos.trBase[0]), -100, 0 },
		{ NETF(clientNum), 7, 0 },
		{ NETF(weapon), 7, 0 },
		{ NETF(weaponModel), 4, 0 },
		{ NETF(lerp.u.anonymous.data[2]), 32, 0 },
		{ NETF(index), 10, 0 },
		{ NETF(solid), 24, 0 },
		{ NETF(lerp.apos.trBase[1]), -100, 0 },
		{ NETF(lerp.apos.trBase[2]), -100, 0 },
		{ NETF(groundEntityNum), -96, 0 },
		{ NETF(lerp.u.anonymous.data[4]), 32, 0 },
		{ NETF(lerp.u.anonymous.data[5]), 32, 0 },
		{ NETF(iHeadIcon), 4, 0 },
		{ NETF(iHeadIconTeam), 2, 0 },
		{ NETF(events[0]), -94, 0 },
		{ NETF(eventParms[0]), -93, 0 },
		{ NETF(lerp.pos.trType), 8, 0 },
		{ NETF(lerp.apos.trType), 8, 0 },
		{ NETF(lerp.apos.trTime), 32, 0 },
		{ NETF(lerp.apos.trDelta[0]), 0, 0 },
		{ NETF(lerp.apos.trDelta[2]), 0, 0 },
		{ NETF(lerp.pos.trDelta[0]), 0, 0 },
		{ NETF(lerp.pos.trDelta[1]), 0, 0 },
		{ NETF(lerp.pos.trDelta[2]), 0, 0 },
		{ NETF(eventSequence), 8, 0 },
		{ NETF(lerp.pos.trTime), -97, 0 },
		{ NETF(events[1]), -94, 0 },
		{ NETF(events[2]), -94, 0 },
		{ NETF(eventParms[1]), -93, 0 },
		{ NETF(eventParms[2]), -93, 0 },
		{ NETF(events[3]), -94, 0 },
		{ NETF(eventParms[3]), -93, 0 },
		{ NETF(lerp.eFlags), -98, 0 },
		{ NETF(lerp.pos.trDuration), 32, 0 },
		{ NETF(lerp.apos.trDelta[1]), 0, 0 },
		{ NETF(time2), -97, 0 },
		{ NETF(loopSound), 8, 0 },
		{ NETF(un2), 32, 0 },
		{ NETF(torsoAnim), 10, 1 },
		{ NETF(legsAnim), 10, 1 },
		{ NETF(fWaistPitch), 0, 1 },
		{ NETF(fTorsoPitch), 0, 1 },
		{ NETF(lerp.u.anonymous.data[3]), 32, 1 },
		{ NETF(lerp.apos.trDuration), 32, 1 },
		{ NETF(partBits[0]), 32, 1 },
		{ NETF(partBits[1]), 32, 1 },
		{ NETF(partBits[2]), 32, 1 },
		{ NETF(partBits[3]), 32, 1 },
	};

	#define NETFE(x) x, sizeof(x) / sizeof(netField_t)

	netFieldList_t netFieldList[] =
	{
		{ NETFE(entityStateFields) },
		{ NETFE(playerEntityStateFields) },
		{ NETFE(corpseEntityStateFields) },
		{ NETFE(itemEntityStateFields) },
		{ NETFE(missleEntityStateFields) },
		{ NETFE(entityStateFields) },
		{ NETFE(scriptMoverStateFields) },
		{ NETFE(soundBlendEntityStateFields) },
		{ NETFE(fxStateFields) },
		{ NETFE(loopFxEntityStateFields) },
		{ NETFE(entityStateFields) },
		{ NETFE(entityStateFields) },
		{ NETFE(helicopterEntityStateFields) },
		{ NETFE(planeStateFields) },
		{ NETFE(vehicleEntityStateFields) },
		{ NETFE(entityStateFields) },
		{ NETFE(entityStateFields) },
		{ NETFE(eventEntityStateFields)}
	};
}
